name: rumos_bank_lending_
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - uvicorn
  - scikit-learn
  - ipykernel
  - numpy
  - pandas
  - mlflow
  - pydantic
  - fastapi
  - cloudpickle
  - matplotlib
  - python=3.10
  - pip
  - requests
  - pytest
