name: Pipeline CI/CD

on:
  push:
    branches: [ testes_full_dataset ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  packages: write

jobs:
  cicd:

    runs-on: ubuntu-latest

    steps:
      - name: Obter repositório
        uses: actions/checkout@v3

      - name: Configurar Docker
        uses: docker/setup-buildx-action@v2

      - name: Iniciar serviços
        run: docker compose up -d

      - name: Criar ambiente para executar testes com o conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: conda.yaml
          activate-environment: rumos_bank_lending_

      - name: Executar testes
        run: conda run --no-capture-output -n rumos_bank_lending_ pytest


      - name: Iniciar sessão no repositório do GitHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Enviar imagem serviço para o repositório do GitHub
        run: docker push ghcr.io/pereiranuno/bank_lending_prediction_service:latest



        